### ISSUE TITLE
Author URL "wwww." 404

### ISSUE THREAD

**Issue by grpace** [Chicago-Digital/ad-google-analytics#1]
Not a big deal but the link on our author URL when you click "Antenna Digital" in the plugin page here has "wwww." which 404s.

![image](https://user-images.githubusercontent.com/10174859/77435907-d9903600-6db0-11ea-9bca-cf4212b1add0.png)

**Comment by scottshefler** [comment]
I think you posted this issue on the wrong plugin this is for the ACF Extended plugin not the Google Anaytics plugin but I fixed it nonetheless!
